# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: HCFS Contract Test

on:
  push:
      branches:
        - master
      paths-ignore:
        - '**.md'
        - '.github/**'
  pull_request:
      branches:
        - master
      paths-ignore:
        - '**.md'
        - '.github/**'
  workflow_dispatch:
      inputs:
          QCLOUD_SECRET_ID:
            description: 'QCLOUD_SECRET_ID' 
          QCLOUD_SECRET_KEY:
            description: 'QCLOUD_SECRET_KEY' 
env:
  DEFAULT_MAVEN_OPTS: -Dmaven.artifact.threads=30 -Dmaven.wagon.http.retryHandler.count=3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
